/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "WeActStudio_MiniSTM32F401.h"
#include "rcc_driver.h"
#include "gpio_driver.h"

/**
 * @brief Configuration GPIO
 */
void gpio_config ();

int main(void)
{
	SystemClock_Config();

	gpio_config();

    /* Loop forever */
	while (true)
	{
		if (GPIO_ReadPin(BUTTON_PORT, BUTTON_PIN) == BUTTON_ACTIVE)
		{
			GPIO_TogglePin(LED_PORT, LED_PIN);
			for (int i = 0; i < 500000; i++);			// Delay
		}

		if (GPIO_ReadPin(BUTTON_PORT, BUTTON_PIN) == BUTTON_ACTIVE)
		{
			GPIO_TogglePin(LED_PORT, LED_PIN);
			for (int i = 0; i < 500000; i++);			// Delay
		}
	}
}

void gpio_config ()
{
	/* Init LED GPIO */
	GPIO_PinConfig_t config = {
		.Pin = LED_PIN,
		.Mode = GPIO_MODE_OUTPUT_PP,
		.Speed = GPIO_SPEED_FREQ_LOW,
		.Pull = GPIO_NOPULL,
	};
	GPIO_Init(LED_PORT, &config);
	GPIO_WritePin(LED_PORT, LED_PIN, LED_OFF);		// Set default led state

	/* Init Button GPIO */
	config.Pin = BUTTON_PIN;
	config.Mode = GPIO_MODE_INPUT;
	config.Pull = GPIO_PULLUP;
	GPIO_Init(BUTTON_PORT, &config);
}
